services:
  - type: web
    name: medical-chat-companion
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn main:app --bind 0.0.0.0:$PORT
    env:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
